### ISSUE TITLE
Feature Request - Titles

### ISSUE THREAD

**Issue by TiagoferMC** [J-CPelletier/webcomix#15]
Is it possible to add an option to title the images the title of the comic strip? As it is right now it's difficult to tell which comic each image corresponds to.

**Comment by J-CPelletier** [comment]
Do you mean like replacing `1.png` to `<comic name>-1.png` with an option? Is there a problem with the way images are associated right now? Normally, every image for a comic should be either in its folder or in the `.cbz` file if you've used the `--cbz`. Is there something wrong on that end?

**Comment by J-CPelletier** [comment]
Resolved by #18.
