### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by kayvax** [J-CPelletier/webcomix#21]
I installed webcomix using pip and can import it in python but quite cant see how it should be used?
There seems to be no cli.

**Comment by J-CPelletier** [comment]
Which OS are you installing it on? If you are on Linux, there might be a problem if the script directory for python isn't in you `PATH` environment variable.

**Comment by kayvax** [comment]
It was me being stupid. Cleaned my system and reinstalled with pip. Works now, sorry for taking your time.
