### ISSUE TITLE
Question: Script Stops after awhile?

### ISSUE THREAD

**Issue by Graem117** [J-CPelletier/webcomix#26]
I am using the CMD to start the script and it runs for a bit, but always stop prematurely before downloading all the comics in the archive, its random too where it stops. Am I doing something wrong? (I am using latest version with the committed nerfnow addition)

**Comment by J-CPelletier** [comment]
Do you have a log or console output of the error that happens?

**Comment by Graem117** [comment]
Sorry, was away. No Error, just says its done downloading, which is not true sadly. I am thinking it might be a connection issue. Not sure if there is any logging for python scripts. Can you tell me how to create one.

**Comment by Graem117** [comment]
If possible one easy solution is the ability to have a start point,. So input a starting point if possible so it does not go over the whole archive.

**Comment by J-CPelletier** [comment]
You could technically create a starting point by going to `webcomix/supported_comics.py` and either:
- Changing the first element(the starting URL) to the one you want to use and continue using `webcomix download Nerfnow`. With that said, the page counter starts back to one when doing that.
- Using the custom command with the information from `webcomix/supported_comics.py`: `webcomix custom Nerfnow --start-url="<your URL here>" --image-xpath="//img[@id='cc-comic']/@src" --next-page-xpath="//a[@class='cc-next']/@href"`

**Comment by J-CPelletier** [comment]
As for determining what the error is through logging, I suspect that it could have something to do with the response body. I wasn't able to reproduce this issue on my end though, so I would need your input on that one. You'd need to add something like `print(response.body)` here: https://github.com/J-CPelletier/webcomix/blob/be1d74a5a405cb07a0feb7a0f2353ac204fd9c44/webcomix/scrapy/download/comic_spider.py#L29 and run the script, which should give you the html of each request. The last request's html would be the one we're looking for.

**Comment by J-CPelletier** [comment]
After looking into it a bit more, I found out that it has to do with the scraper getting a `403 Forbidden` from the Cloudflare hosting at some point. From what I've read online, you could manage this issue by getting the webcomic as if it were a javascript-heavy website. See [here](https://github.com/J-CPelletier/webcomix#downloading-comics-on-javascript-heavy-websites) for more information. I'll also add an option to start the download from a specific page number.

**Comment by Graem117** [comment]
Awsome thanks for that!! Question for downloading docker, do I install the desktop docker version or the open source?

**Comment by J-CPelletier** [comment]
For Windows, I'd recommend installing the [Docker Desktop for Windows](https://docs.docker.com/docker-for-windows/install/) if you're on Windows 10 Pro/Education/Enterprise, and [Docker Toolbox for Windows](https://docs.docker.com/toolbox/toolbox_install_windows/) if you're on Windows 10 Home.

**Comment by Graem117** [comment]
Okay I installed the docker toolbox since I had Home version, now for running this command
docker run -p 8050:8050 scrapinghub/splash
Should I have docker running?

**Comment by J-CPelletier** [comment]
Yes, docker should be running for it to work. Once you've ran this command, you should be able to visit `localhost:8050` in your browser and get a website called `Splash`.

**Comment by Graem117** [comment]
Alright I have docker running, but when I run the command on cmd I get this message

docker: Error response from daemon: driver failed programming external connectivity on endpoint funny_elion (7f9086be96c2e3ea1e82659e456a6071f767726d5186928cf55b818d11bcf7bc): Bind for 0.0.0.0:8050 failed: port is already allocated.

I thought I got it working but the website splash does not show on the browser

**Comment by J-CPelletier** [comment]
This probably has to do with a previously started server still being in use. The command above(`docker run -p 8050:8050 scrapinghub/splash`) runs a server on your machine at port `8050`. Check if you still have a server running with `docker ps` and kill the previous one with `docker kill <container id>`(the container id can be gotten with the previous command). You can also change the port you'd need to use in your browser by change the first `8050` in the `docker run` command.

**Comment by Graem117** [comment]
Oh okay it is running now, Although chrome just errors on "ERR_INVALID_HTTP_RESPONSE" and Firefox loads forever when localhost:8050 is loaded. Hopefully I can still make it work.
![image](https://user-images.githubusercontent.com/67132870/85961793-df328480-b97a-11ea-8f90-12c3598c2d7b.png)
Now when I got to download Nerfnow I go
Webcomix Custom Nerfnow -j
URL: https://www.nerfnow.com/comic/4
IMG: //div[@id='comic']//img/@src
Next: //li[@id='nav_next']//a/@href
then boom

**Comment by J-CPelletier** [comment]
Were you able to download Nerfnow this way?

**Comment by Graem117** [comment]
Sorry was away for awhile, I did just tried it and I am getting this error
c:\users\graem paterson\appdata\local\programs\python\python38-32\lib\site-packages\scrapy_splash\request.py:41: ScrapyDeprecationWarning: Call to deprecated function to_native_str. Use to_unicode instead.
  url = to_native_str(url)
Nerfnow could not be accessed with webcomix.
Chances are the website you're trying to download images from doesn't want to be scraped.
Aborted!

**Comment by J-CPelletier** [comment]
I haven't been able to reproduce this bug. I've published a new version of webcomix. Download it to test your command again and if it fails again, try it with the verbose option(`-v`) and post the end of the logs(like the last 50 lines) here.

**Comment by J-CPelletier** [comment]
After looking at this again, the issue you had 5 days ago were related to #29. I'll be releasing an update to fix this issue today.

**Comment by Graem117** [comment]
Worked like a charm man, its working now. Start page also Helped a ton!

**Comment by Graem117** [comment]
Thanks for making this and adjusting the program, its very good stuff.

**Comment by J-CPelletier** [comment]
Glad to hear that it's now working for you. Thanks for the feedback!
