### ISSUE TITLE
Vgcats different xpaths

### ISSUE THREAD

**Issue by Graem117** [J-CPelletier/webcomix#32]
Hey I notice for vgcats the xpaths are different compared to other webcomics, is there a way to make these work?

webcomix custom Vgcats --start-url="https://www.vgcats.com/comics/?strip_id=0" --image-xpath="/html/body/center/table/tbody/tr[5]/td/img" --next-page-xpath="/html/body/center/table/tbody/tr[2]/td[4]/a[2]"

**Comment by J-CPelletier** [comment]
You should be able to take some of the examples in the [supported_comics.py](https://github.com/J-CPelletier/webcomix/blob/master/webcomix/supported_comics.py) file(where you have `start_url`, `image_xpath`, and `next_page_xpath`, in this order). When doing XPath expressions, you should make sure that you use things like `//<tag>`, which selects the tag even if there are multiple children depths separating the previous tag with this one. It should make XPath expressions less prone to break when the websites get redesigned.

With this a a few other tricks you can see in the [supported_comics.py](https://github.com/J-CPelletier/webcomix/blob/master/webcomix/supported_comics.py) file, I arrived to these expressions:

```webcomix custom Vgcats --start-url="https://www.vgcats.com/comics/?strip_id=0" --image-xpath="//table//img[contains(@src, 'images')]/@src" --next-page-xpath="//table//a[img[contains(@src, 'next')]]/@href"```

**Comment by Graem117** [comment]
Ah sorry got very busy, what you provided worked wanderfully for me. Will keep this in mind in the future!
