### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by SurpriseFox** [J-CPelletier/webcomix#36]
https://www.housepetscomic.com/ would be nice to see.
Image xpath: //div[@id='comic']//img/@src
Next page xpath: //div[@id='comic']//@href
Works well. Thanks for the great scripts.

**Comment by J-CPelletier** [comment]
@SurpriseFox I've added it to the list with `webcomix` 3.4.2, so you should now be able to download it by installing the latest update. Sadly, I was getting blocked by Cloudflare while testing it. Just tell me if you're getting an error like `Your download has been blocked by the hosting website. Please try again later.` while using it, and I'll try to find some workaround if that's not just on my end.

**Comment by SurpriseFox** [comment]
Yes, that does happen. I don't know Python, but I solved the issue by drastically restricting my internet speed (to around 150kbps or one comic per second) and was able to do a complete archive in two groupings using the last url requested as a new starting position. It appears the issue is the rate that it is making requests triggering some kind of protection. If I can make a suggestion, a flag like the one for making cbz outputs that causes the program to slow down the access rate may solve it. 
Also, thank you, this software has been quite useful.

**Comment by J-CPelletier** [comment]
@SurpriseFox With `webcomix` 3.5.0, I managed to download it in one go by retrying in case we get a 403 Forbidden. Try it on your end and tell me if it works. Great to hear that the software has been working well for you!

**Comment by J-CPelletier** [comment]
@SurpriseFox Have you been able to test it out?

**Comment by yuukiw** [comment]
i would need some help i tried to make a costum comand to dl sailor moon ranko but it only finds two page.

The line i use is 
webcomix custom xkcd --start-url=http://sailorranko.com/archive/001page001.html  --next-page-xpath="/html/body/div[1]/div[2]/div[2]/p[2]/span/a[1]/@href" --image-xpath="/html/body/div[1]/div[2]/div[2]/img"

whats wrong about it?

**Comment by J-CPelletier** [comment]
@yuukiw The problem with your command is that your XPath selectors are too flaky. They require the website to have a very specific layout which could potentially change slightly from page to page. For example, getting the second link in the `next_page_xpath` means that once the previous links become active in the second page, you cannot find the next page anymore(hence why you only find two pages). You should use `//` when searching for a node that isn't a direct child in the html tree, and probably not rely on the order of the different `div` elements when possible. For example, you should try something like this:

`webcomix custom SailorRanko --start-url=http://sailorranko.com/archive/001page001.html --next-page-xpath="//div[@id='comic']//a[text()='Next Page']/@href" --image-xpath="//div[@id='comic']//img/@src"`

**Comment by yuukiw** [comment]
ah thats why it never worked, didn't know about the // thing

**Comment by J-CPelletier** [comment]
Glad to hear that I've been able to help! I'll be closing this issue, since I've added Housepets and it doesn't seem like @SurpriseFox is responding.
