### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by erpbridge** [J-CPelletier/webcomix#5]
New Comic: ElGoonishShive
webcomix custom --comic_name=ElGoonishShive --start_url=http://www.egscomics.com/comic/2002-01-21 --next_page_xpath="//a[@class='cc-next']/@href" --image_xpath="//div[@id='cc-comicbody']//img/@src"

**Comment by J-CPelletier** [comment]
Sorry for taking so long to respond, I just noticed that someone had left two issues here. I'll be adding this shortly.
