### ISSUE TITLE
Add --end-url

### ISSUE THREAD

**Issue by nfowlie** [J-CPelletier/webcomix#77]
Add a feature similar to --start-url that specifies the last page of a comic to download, possibly --end-url.
A use case would be to download web comics that are chapter based and save each chapter as a cbz, giving a start and end page for the given chapter.

**Comment by J-CPelletier** [comment]
Sounds like a good idea!

**Comment by nfowlie** [comment]
I was able to get this feature working locally.  Excited to see this feature added to the project.

**Comment by J-CPelletier** [comment]
I'll be creating the 3.8.0 release with the new option `--end-url` shortly.
